import Head from 'next/head'
import Image from 'next/image'
import DiscoverItem from '../components/DiscoverItem'
import Nav from '../components/Nav'
import styles from '../styles/Home.module.css'

const JSONData = [
  {
    name: 'Call of Duty:  Cold War',
    img: 'https://bnetcmsus-a.akamaihd.net/cms/blog_header/6a/6ADE9XLH1RZS1602609187570.jpg'
  },
  {
    name: 'Minecraft',
    img: 'https://image.api.playstation.com/vulcan/img/cfn/11307x4B5WLoVoIUtdewG4uJ_YuDRTwBxQy0qP8ylgazLLc01PBxbsFG1pGOWmqhZsxnNkrU3GXbdXIowBAstzlrhtQ4LCI4.png'
  },
  {
    name: 'Madden 21',
    img: 'https://cdn.mos.cms.futurecdn.net/mJDjxRHpe7GvgdWS3BVNeW.jpg',
  },
  {
    name: 'Mortal Kombat 11',
    img: 'https://image.api.playstation.com/vulcan/ap/rnd/202010/0822/GuWErMI21uTbfZ6ohfiF7Yt0.jpg',
  },
  {
    name: 'Brawlhalla',
    img: 'https://s1.dmcdn.net/v/SsTQ21WNicCoqb9u0/x1080',
  },
  {
    name: 'NBA 2K21',
    img: 'https://www.newuniversity.org/wp-content/uploads/2020/11/2k21.jpg',
  },
  {  
  name: 'Super Smash Bros: Ultimate',
  img: 'https://cdn02.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_SuperSmashBrosUltimate_02_image1600w.jpg',
  },
  {
    name: 'Rocket League',
    img: 'https://www.nintendo.com//content/dam/noa/en_US/games/switch/r/rocket-league-switch/rocket-league-switch-hero.jpg',
  }
]

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>The Pot.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossOrigin="anonymous" />
      </Head>
      <Nav />
      <div className="w-full p-0 sm:p-6 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 pb-24">
      {
        JSONData.map((val: any) => {
          return <DiscoverItem  val={val}/>
        })
      }
      </div>
    </div>
  )
}
